### ISSUE TITLE
Byte av Fragment medans en HttpConnection är öppen orsakar en krasch

### ISSUE THREAD

**Issue by atemmel** [atemmel/antons-skafferi-app#43]
**Problem:** Se titel.

**Möjlig lösning 1:** Undersök om användaren kan förbjudas från att byta Fragment medans en HttpConnection är öppen.

**Möjlig Lösning 2:** Undersök om det går att avbryt eventuella aktiva HttpRequests vid byte av Fragment.

**Comment by atemmel** [comment]
Jag kan ha åtgärdat delar av detta bekymmer genom att introducera null checks lite kors och tvärs i appen, men kan inte avgöra om problemet är helt borta.

Ni får gärna fortsätta damptesta mobilapplikationen då jag inte är helt övertygad att allt är åtgärdat.

**Comment by Ninhow** [comment]
Volley boys

**Comment by Ninhow** [comment]
Eeeeeea

Den fre 13 dec. 2019 22:24atemmel <notifications@github.com> skrev:
