### ISSUE TITLE
Logga endast in en gång

### ISSUE THREAD

**Issue by OscarFredriksson** [atemmel/antons-skafferi-app#9]
**Problem:** Användare behöver logga in varje gång appen startas. Bör endast behöva göras en gång och sedan ska användaren vara inloggad tills denna väljer att logga ut manuellt. 

**Möjlig lösning:** Enligt toppsvaret i [denna tråd](https://stackoverflow.com/questions/9370293/add-a-remember-me-checkbox) på stacken bör detta gå att spara i ett _SharedPreferences_  objekt som sedan kan läsas in varje gång appen startas.

**Comment by atemmel** [comment]
Fixed
